"""Managed census of projects and users for the nightly sync.

The census answers two questions the sync config used to require hand-written
answers for: *which .driveprojx files are real projects* (vs. backups, copies,
test junk) and *who is behind each DriveWorks display name*. Instead of
authoring globs and alias maps blind, the census is generated by scanning and
curated by a human filling in blanks:

- `users` maps every DriveWorks display name ever seen to an identity string
  ("Name <email>") — or null while unmapped. The nightly sync auto-appends
  new names as null; unmapped names are flagged on the dashboard and resolved
  in the GUI (Tools > Manage Nightly Sync) or via `--census --map`.
- `projects` maps every project name to its source path and a disposition:
  "pending" (newly discovered, syncs normally, awaiting review), "track", or
  "ignore" (skipped by the sync; archive history is kept).
- `conflicts` lists same-name collisions the sync refused to guess about.

The file lives at data_dir/census.json (config key `census_path` overrides)
and is safe to hand-edit; scans and syncs only ever *add* entries or update
paths — they never overwrite a human's mapping or disposition.

Mapping a user also heals history: metrics rows recorded under the raw
display name are retroactively updated to the mapped identity, so per-user
charts read as if the mapping had always existed. Git history is deliberately
not rewritten — old commits keep the raw name the file carried at the time.
"""

from __future__ import annotations

import json
import re
import sqlite3
import zipfile
from pathlib import Path

# DriveWorks writes the user who last saved the project into designMaster.xml
# as "special variables". DWCurrentUserDisplayName is the human name; the email
# is often blank, so name is the primary key.
_DISPLAY_RE = re.compile(r'StoreName="DWCurrentUserDisplayName"\s+Value="([^"]*)"')
_EMAIL_RE = re.compile(r'StoreName="DWCurrentUserEmailAddress"\s+Value="([^"]*)"')

DISPOSITIONS = ('pending', 'track', 'ignore')


def census_path(cfg: dict) -> Path:
    return Path(cfg['census_path']) if cfg.get('census_path') else Path(cfg['data_dir']) / 'census.json'


def load_census(path: Path) -> dict:
    census = {'schema': 1, 'users': {}, 'projects': {}, 'conflicts': []}
    if path.is_file():
        census.update(json.loads(path.read_text(encoding='utf-8')))
    return census


def save_census(path: Path, census: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    census = {**census,
              'users': dict(sorted(census['users'].items())),
              'projects': dict(sorted(census['projects'].items()))}
    path.write_text(json.dumps(census, indent=2, ensure_ascii=False) + '\n',
                    encoding='utf-8')


def snapshot(census: dict) -> str:
    """Stable serialization used to detect whether a run changed the census."""
    return json.dumps(census, sort_keys=True)


def seed_from_config(census: dict, cfg: dict) -> None:
    """Import legacy `author_aliases` mappings as census users (non-destructive:
    a human-filled census entry is never overwritten)."""
    for raw, ident in cfg.get('author_aliases', {}).items():
        if not census['users'].get(raw):
            census['users'][raw] = ident


def ensure_user(census: dict, display: str) -> None:
    """Register a newly seen display name as unmapped (null)."""
    if display and display not in census['users']:
        census['users'][display] = None


def ensure_project(census: dict, name: str, rel_path: str) -> dict:
    """Register a newly discovered project as pending; move an existing entry's
    path when the file moved (same name, old path gone). Returns the entry."""
    entry = census['projects'].get(name)
    if entry is None:
        entry = {'path': rel_path, 'disposition': 'pending'}
        census['projects'][name] = entry
    return entry


def unmapped_users(census: dict) -> list:
    return sorted(raw for raw, ident in census['users'].items() if not ident)


def pending_projects(census: dict) -> list:
    return sorted((name, e.get('path', '')) for name, e in census['projects'].items()
                  if e.get('disposition') == 'pending')


def read_last_saver(project_root: Path) -> tuple:
    """(display_name, email) of the DriveWorks user who last saved the project,
    read from its designMaster.xml. ('', '') if unavailable."""
    dm = project_root / 'driveProj' / 'designMaster.xml'
    if not dm.is_file():
        return ('', '')
    return _extract_saver(dm.read_bytes())


def read_last_saver_from_zip(zip_path: Path) -> tuple:
    """Same as read_last_saver but reads the designMaster.xml member straight
    out of the .driveprojx without extracting — cheap enough to scan a whole
    share."""
    try:
        with zipfile.ZipFile(zip_path, 'r') as zf:
            for member in zf.namelist():
                if member.lower().endswith('designmaster.xml'):
                    return _extract_saver(zf.read(member))
    except (OSError, zipfile.BadZipFile):
        pass
    return ('', '')


def _extract_saver(data: bytes) -> tuple:
    text = data.decode('utf-8', 'replace')
    d = _DISPLAY_RE.search(text)
    e = _EMAIL_RE.search(text)
    return (d.group(1).strip() if d else '',
            e.group(1).strip() if e else '')


def resolve_owner(project: str, project_root: Path, cfg: dict, census: dict) -> tuple:
    """Resolve attribution for a project's change.

    Returns (git_author, db_owner, unmapped_display):
    - git_author: "Name <email>" for the commit ('' = sync's own identity)
    - db_owner: what the metrics rows record — the mapped identity, or the
      *raw display name* when unmapped so healing can find the rows later
    - unmapped_display: the raw name if it needs a census entry, else None

    Precedence: explicit config `owners` entry > census users map > legacy
    `author_aliases` > the raw last-saver from the file.

    `project` may be a namespaced census key ("<source>/<name>") under a site
    config; an `owners` entry matches by the full key or the plain name.
    """
    owners = cfg.get('owners', {})
    override = owners.get(project)
    if not override and '/' in project:
        override = owners.get(project.split('/', 1)[1])
    if override:
        return override, override, None
    if not cfg.get('derive_author_from_file'):
        return '', '', None
    display, email = read_last_saver(project_root)
    if not display:
        return '', '', None
    ident = census['users'].get(display) or cfg.get('author_aliases', {}).get(display)
    if ident:
        return ident, ident, None
    git_author = f'{display} <{email}>' if email else f'{display} <>'
    return git_author, display, display


def heal_metrics(conn: sqlite3.Connection, census: dict) -> int:
    """Retroactively update metrics rows recorded under a raw display name to
    the now-mapped identity. Covers the current convention (owner = raw name)
    and the pre-census one (owner = 'raw <>' / 'raw <email>' is left alone —
    it already carries an email and is a usable identity). Returns rows
    updated."""
    healed = 0
    for raw, ident in census['users'].items():
        if not ident or ident == raw:
            continue
        for table in ('category_changes', 'element_changes'):
            cur = conn.execute(f'UPDATE {table} SET owner=? WHERE owner=? OR owner=?',
                               (ident, raw, f'{raw} <>'))
            healed += cur.rowcount
    return healed


# ------------------------------------------------------------------ scan ----

def scan(cfg: dict, census: dict, find_projects_fn) -> dict:
    """Walk every configured source (honouring excludes) and the metrics DB,
    adding every unseen project and display name to the census. Never
    overwrites existing entries. Returns a summary dict."""
    sources = cfg.get('sources_resolved') or {'': {
        'source_dir': Path(cfg['source_dir']),
        'exclude': cfg.get('exclude', []),
        'recursive': cfg.get('recursive', True),
    }}
    new_projects, new_users = [], []

    for sname, scfg in sources.items():
        source = Path(scfg['source_dir'])
        if not source.is_dir():
            continue
        for zip_path in find_projects_fn(source, scfg.get('recursive', True),
                                         scfg.get('exclude', [])):
            key = f'{sname}/{zip_path.stem}' if sname else zip_path.stem
            rel = zip_path.relative_to(source).as_posix()
            if key not in census['projects']:
                new_projects.append(key)
            ensure_project(census, key, rel)
            display, _email = read_last_saver_from_zip(zip_path)
            if display and display not in census['users']:
                new_users.append(display)
            ensure_user(census, display)

    # Harvest raw display names already recorded in the metrics DB (from syncs
    # that ran before those users were mapped).
    db_path = Path(cfg['data_dir']) / 'metrics.sqlite'
    if db_path.is_file():
        conn = sqlite3.connect(db_path)
        try:
            for (owner,) in conn.execute(
                    'SELECT DISTINCT owner FROM element_changes WHERE owner IS NOT NULL'):
                raw = owner[:-3].strip() if owner.endswith(' <>') else owner
                if raw and '<' not in raw and raw not in census['users']:
                    new_users.append(raw)
                    ensure_user(census, raw)
        finally:
            conn.close()

    return {'new_projects': sorted(new_projects), 'new_users': sorted(new_users),
            'unmapped': unmapped_users(census), 'pending': pending_projects(census)}


# ------------------------------------------------------------------- cli ----

def _apply_edits(census: dict, maps: list, tracks: list, ignores: list) -> list:
    """Apply --map/--track/--ignore edits. Returns human-readable notes."""
    notes = []
    for m in maps:
        raw, _, ident = m.partition('=')
        raw, ident = raw.strip(), ident.strip()
        if not raw or not ident:
            raise SystemExit(f'--map expects RAW=Name <email>, got: {m!r}')
        census['users'][raw] = ident
        notes.append(f'mapped user: {raw} -> {ident}')
    for name in tracks:
        entry = census['projects'].get(name)
        if entry is None:
            raise SystemExit(f'--track: no project named {name!r} in the census')
        entry['disposition'] = 'track'
        notes.append(f'tracking project: {name}')
    for name in ignores:
        entry = census['projects'].get(name)
        if entry is None:
            raise SystemExit(f'--ignore: no project named {name!r} in the census')
        entry['disposition'] = 'ignore'
        notes.append(f'ignoring project: {name}')
    return notes


def main(argv=None) -> int:
    """`--census` mode: scan the share into the census, apply any edits, heal
    the metrics DB, and print what still needs attention."""
    import argparse
    from .sync import load_config, find_projects  # local import: sync imports us

    parser = argparse.ArgumentParser(
        description='Scan projects/users into the sync census and manage dispositions')
    parser.add_argument('config', type=Path, help='Path to the nightly sync config JSON')
    parser.add_argument('--map', action='append', default=[], metavar='RAW=IDENTITY',
                        help='Map a display name: --map "Zach=Zach Miller <z@x.com>"')
    parser.add_argument('--track', action='append', default=[], metavar='PROJECT',
                        help='Set a project disposition to track')
    parser.add_argument('--ignore', action='append', default=[], metavar='PROJECT',
                        help='Set a project disposition to ignore')
    parser.add_argument('--no-scan', action='store_true',
                        help='Apply edits only; skip the share scan')
    args = parser.parse_args(argv)

    cfg = load_config(args.config)
    cpath = census_path(cfg)
    census = load_census(cpath)
    seed_from_config(census, cfg)

    if not args.no_scan:
        summary = scan(cfg, census, find_projects)
        print(f'scan: {len(census["projects"])} project(s), '
              f'{len(census["users"])} user name(s) '
              f'({len(summary["new_projects"])} project(s) and '
              f'{len(summary["new_users"])} user(s) newly discovered)')

    for note in _apply_edits(census, args.map, args.track, args.ignore):
        print(note)

    save_census(cpath, census)
    print(f'census saved: {cpath}')

    db_path = Path(cfg['data_dir']) / 'metrics.sqlite'
    if db_path.is_file():
        conn = sqlite3.connect(db_path, isolation_level=None)
        try:
            healed = heal_metrics(conn, census)
        finally:
            conn.close()
        if healed:
            print(f'healed {healed} metrics row(s) with newly mapped identities')

    pending = pending_projects(census)
    unmapped = unmapped_users(census)
    if pending:
        print(f'\n{len(pending)} project(s) pending disposition:')
        for name, path in pending:
            print(f'  {name}  ({path})')
    if unmapped:
        print(f'\n{len(unmapped)} unmapped user(s):')
        for raw in unmapped:
            print(f'  {raw}')
    if not pending and not unmapped:
        print('nothing needs attention')
    return 0
